### ISSUE TITLE
Consider making this user script into a chrome plugin

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/youtube-subcriptions-watch-later#1]
If this script runs stable for a time, I might consider pouring this into a legitimate plugin.

This article may help me do that:
https://justin.kelly.org.au/how-to-create-a-google-chrome-extension-from/

**Comment by natewind** [comment]
Chrome sometimes disables extensions that Google doesn’t like, so it’s not a great idea.
Scripts give the user more freedom.
Also, Firefox users would need a separate plugin.

**Comment by ackoujens** [comment]
@natewind Thanks man. Saving me some researching-madness. (and allot of whiskey)
